// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class HomeworkTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void createauser() {
    driver.Navigate().GoToUrl("https://qauto.forstudy.space/");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 800);
    driver.FindElement(By.CssSelector(".hero-descriptor_btn")).Click();
    driver.FindElement(By.Id("signupName")).Click();
    driver.FindElement(By.Id("signupName")).SendKeys("Olga");
    driver.FindElement(By.Id("signupLastName")).SendKeys("Duziak");
    driver.FindElement(By.Id("signupEmail")).SendKeys("olya1@mail.com");
    driver.FindElement(By.Id("signupPassword")).SendKeys("1302Niki");
    driver.FindElement(By.Id("signupRepeatPassword")).SendKeys("1302Niki");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(1)")).Click();
  }
  [Test]
  public void addcar() {
    driver.Navigate().GoToUrl("https://qauto.forstudy.space/panel/garage");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 800);
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.Id("addCarBrand")).Click();
    {
      var dropdown = driver.FindElement(By.Id("addCarBrand"));
      dropdown.FindElement(By.XPath("//option[. = 'Fiat']")).Click();
    }
    driver.FindElement(By.Id("addCarMileage")).Click();
    driver.FindElement(By.Id("addCarMileage")).SendKeys("149");
    driver.FindElement(By.Id("addCarMileage")).Click();
    driver.FindElement(By.CssSelector(".modal-footer > .btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".modal-footer > .btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
  }
  [Test]
  public void addexpense() {
    driver.Navigate().GoToUrl("https://qauto.forstudy.space/panel/garage");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 800);
    driver.FindElement(By.CssSelector(".sidebar > .btn:nth-child(2)")).Click();
    driver.FindElement(By.Id("carSelectDropdown")).Click();
    driver.FindElement(By.CssSelector(".car-select-dropdown_item:nth-child(2)")).Click();
    driver.FindElement(By.Id("carSelectDropdown")).Click();
    driver.FindElement(By.CssSelector(".car-select-dropdown_item:nth-child(1)")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("150");
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("151");
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    {
      var element = driver.FindElement(By.Id("addExpenseMileage"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("152");
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("153");
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("154");
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("155");
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("156");
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("157");
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("158");
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    {
      var element = driver.FindElement(By.Id("addExpenseMileage"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.Id("addExpenseMileage")).SendKeys("159");
    driver.FindElement(By.Id("addExpenseMileage")).Click();
    driver.FindElement(By.Id("addExpenseLiters")).Click();
    driver.FindElement(By.Id("addExpenseLiters")).SendKeys("10");
    driver.FindElement(By.Id("addExpenseTotalCost")).SendKeys("10");
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(2)")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
  }
  [Test]
  public void checknameandlastname() {
    driver.Navigate().GoToUrl("https://qauto.forstudy.space/panel/garage");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 800);
    driver.FindElement(By.LinkText("Profile")).Click();
    driver.FindElement(By.CssSelector(".btn-primary")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.Id("editProfileName")).Click();
    {
      string value = driver.FindElement(By.Id("editProfileName")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("Olga"));
    }
    driver.FindElement(By.Id("editProfileLastName")).Click();
    {
      string value = driver.FindElement(By.Id("editProfileLastName")).GetAttribute("value");
      Assert.That(value, Is.EqualTo("Duziak"));
    }
  }
  [Test]
  public void delete() {
    driver.Navigate().GoToUrl("https://qauto.forstudy.space/panel/garage");
    driver.Manage().Window.Size = new System.Drawing.Size(1536, 800);
    driver.FindElement(By.LinkText("Settings")).Click();
    driver.FindElement(By.CssSelector(".btn-danger-bg")).Click();
    driver.FindElement(By.CssSelector(".btn-danger")).Click();
  }
}
